version: "3.2"

services:
  server:
    build: ./server
    restart: always
    ports: 
      - 3000:3000
    networks:
      - local

  db:
    image: mongo:3.6
    networks:
      - local
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
  
volumes:
  data:

networks:
  local: